// ---------------------------
// This file was generated by Nango (v0.58.4)
// You can version this file
// ---------------------------

export interface UpdateMessageInput {
  ts: string;
  channel: string;
  text: string;
};

export interface UpdateMessageOutput {
  ok: boolean;
  channel?: string | undefined;
  ts?: string | undefined;
  message?: string | undefined;
  warning?: string | undefined;
  error?: string | undefined;
  raw_json: string;
};
